"""leave type — planned, unplanned, emergency

Adds three new leave_type enum values: planned, unplanned, emergency —
replacing casual/sick/earned/unpaid/comp_off as the types the Apply for
Leave form offers, per an explicit request to change the list rather than
add to it.

WHY THE OLD VALUES ARE NOT REMOVED
----------------------------------------
Postgres cannot drop a value from an ENUM without recreating the type and
rewriting every column that uses it — the same constraint
20260915_1000_work_from_home.py's own downgrade() already documents for
this exact type. Any existing leave row still carrying casual/sick/earned/
unpaid/comp_off keeps working unmodified; those values simply become
unreachable from the Apply for Leave form going forward, the same way this
project already tolerates an unused value rather than a destructive
rewrite.

sick and unpaid are also added alongside the three explicitly requested
(planned, unplanned, emergency) — SICK LEAVE ALREADY EXISTS AS A VALUE, no
work needed there beyond keeping it selectable in the frontend list. UNPAID
is genuinely new phrasing-wise but the existing 'unpaid' value already
covers it, so no new enum value was needed for it — this migration only
adds the three that had no existing equivalent.

WHY THIS IS HAND-WRITTEN RATHER THAN AUTOGENERATED
---------------------------------------------------
Alembic's autogenerate does not detect new values on an existing Postgres
ENUM — see 20260915_1000_work_from_home.py's own docstring for the same
note. ALTER TYPE ... ADD VALUE also cannot run inside a transaction block
on older Postgres, hence the autocommit block.
"""

from alembic import op

revision = "d1f6b8c92a37"
down_revision = "c9e2a5f31b48"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE leave_type ADD VALUE IF NOT EXISTS 'planned'")
        op.execute("ALTER TYPE leave_type ADD VALUE IF NOT EXISTS 'unplanned'")
        op.execute("ALTER TYPE leave_type ADD VALUE IF NOT EXISTS 'emergency'")


def downgrade() -> None:
    # Postgres cannot remove a value from an ENUM — see this file's own
    # docstring and the identical note in 20260915_1000_work_from_home.py.
    pass