"""task start date and real timestamp defaults

Revision ID: bd1219610f40
Revises: 56cfb42b4f40
Create Date: 2026-09-15 08:54:13.198505
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate writes `pgvector.sqlalchemy.vector.VECTOR(...)` for the face
# embedding column but does not add the import for it, so a generated migration
# fails with NameError the first time it runs. Importing it in the template
# means every migration from here on is correct without anyone remembering.
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = 'bd1219610f40'
down_revision: Union[str, None] = '56cfb42b4f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance_days', 'computed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('face_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('punch_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.add_column('tasks', sa.Column('start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'start_date')
    op.alter_column('punch_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-09-15 05:58:05.215701+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('face_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-09-15 05:58:05.215701+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-09-15 05:58:05.215701+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('attendance_days', 'computed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-09-15 05:58:05.215701+00'::timestamp with time zone"),
               existing_nullable=False)
    # ### end Alembic commands ###
