"""work from home

Adds two enum values:
  leave_type         + work_from_home
  attendance_status  + WORK_FROM_HOME

WHY THIS IS HAND-WRITTEN RATHER THAN AUTOGENERATED
---------------------------------------------------
Alembic's autogenerate does not detect new values on an existing Postgres ENUM.
It compares tables and columns, not the contents of a type — so it would have
produced an empty migration and the application would have failed at runtime
with "invalid input value for enum".

ALTER TYPE ... ADD VALUE also cannot run inside a transaction block on older
Postgres, hence the autocommit block.
"""

from alembic import op

revision = "c4a81f3e7d20"
down_revision = "bd1219610f40"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE leave_type ADD VALUE IF NOT EXISTS 'work_from_home'")
        op.execute("ALTER TYPE attendance_status ADD VALUE IF NOT EXISTS 'WORK_FROM_HOME'")


def downgrade() -> None:
    # Postgres cannot remove a value from an ENUM. Undoing this means recreating
    # both types and rewriting every column that uses them — far more dangerous
    # than leaving two unused values behind.
    #
    # Saying so here is better than a silent `pass` that looks like an oversight.
    pass
